

root_directory = 'C:\Users\matt\Downloads\jumpAeroData\matlab_stuff\data';
files = dir([root_directory,'\**\*.mat']);

xlims = [20,21]; xlims = [ -inf,inf ];

for ii = 1:numel(files)

    %% Import APM File
    file = fullfile(files(ii).folder,files(ii).name);

    [pathstr,name,ext] = fileparts(file);
    fprintf('%d / %d : Processing %s\n',ii,length(files),file);

    % Get the data
    fds = load(file); ...
        fds = fds.fdsExport;

    t = kVIS_fdsGetChannel(fds, 'omegaZ','Time'); ...
        t = t - t(1);

    p = kVIS_fdsGetChannel(fds, 'omegaX','Var_1');
    q = kVIS_fdsGetChannel(fds, 'omegaY','Var_1');
    r = kVIS_fdsGetChannel(fds, 'omegaZ','Var_1');

    p_cmd = kVIS_fdsGetChannel(fds, 'w_cmd','Var_1')*57.2;
    q_cmd = kVIS_fdsGetChannel(fds, 'w_cmd','Var_2')*57.2;
    r_cmd = kVIS_fdsGetChannel(fds, 'w_cmd','Var_3')*57.2;

    pitch_cmd = kVIS_fdsGetChannel(fds, 'pitch','Var_1')*57.2;

    M1 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_1');
    M2 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_2');
    M3 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_3');
    M4 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_4');
    M5 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_5');
    M6 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_6');
    M7 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_7');
    M8 = kVIS_fdsGetChannel(fds, 'motor_speed','Var_8');

    M1cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_1');
    M2cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_2');
    M3cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_3');
    M4cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_4');
    M5cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_5');
    M6cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_6');
    M7cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_7');
    M8cmd = kVIS_fdsGetChannel(fds, 'n_cmd','Var_8');

    I1 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_1');
    I2 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_2');
    I3 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_3');
    I4 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_4');
    I5 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_5');
    I6 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_6');
    I7 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_7');
    I8 = kVIS_fdsGetChannel(fds, 'current_cmd','Var_8');

    blade_pitch_channel = 'bp_cmd';

    if (1)
        BP1 = kVIS_fdsGetChannel(fds, 'bladePitch0','Var_1');
        BP2 = kVIS_fdsGetChannel(fds, 'bladePitch1','Var_1');
        BP3 = kVIS_fdsGetChannel(fds, 'bladePitch2','Var_1');
        BP4 = kVIS_fdsGetChannel(fds, 'bladePitch3','Var_1');
        BP5 = kVIS_fdsGetChannel(fds, 'bladePitch4','Var_1');
        BP6 = kVIS_fdsGetChannel(fds, 'bladePitch5','Var_1');
        BP7 = kVIS_fdsGetChannel(fds, 'bladePitch6','Var_1');
        BP8 = kVIS_fdsGetChannel(fds, 'bladePitch7','Var_1');
    else
        BP1 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_1');
        BP2 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_2');
        BP3 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_3');
        BP4 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_4');
        BP5 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_5');
        BP6 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_6');
        BP7 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_7');
        BP8 = kVIS_fdsGetChannel(fds, blade_pitch_channel,'Var_8');
    end



    if (xlims(2)-xlims(1)<4)
    markerStyle = 'o';
    else
        markerStyle = 'none';
    end

    a = lines;


    figure(ii+10); clf; set(gcf,'name',name);
    subplot(4,2,1); hold all; grid on; grid minor; ...
        plot(t,p,'-','marker',markerStyle); ...
        plot(t,q,'-','marker',markerStyle); ...
        plot(t,r,'-','marker',markerStyle); ...
        ylim([-25,25])
    xlabel('Time [ s ]'); ylabel('Angular Rate'); ...
        yyaxis right; ...
        plot(t,pitch_cmd); ...
        xlim(xlims);
    subplot(4,2,2); hold all; grid on; grid minor; ...
        plot(t,p,'-','marker',markerStyle); ...
        plot(t,q,'-','marker',markerStyle); ...
        plot(t,r,'-','marker',markerStyle); ...
        plot(t,p_cmd,'--','marker',markerStyle,'color',a(1,:)); ...
        plot(t,q_cmd,'--','marker',markerStyle,'color',a(2,:)); ...
        plot(t,r_cmd,'--','marker',markerStyle,'color',a(3,:)); ...
        ylim([-25,25]); xlim(xlims); ...
        xlabel('Time [ s ]'); ylabel('Angular Rate'); ...
        

    subplot(4,2,3); hold all; grid on; grid minor; ...
        plot(t,M1,'-','color',a(1,:),'marker',markerStyle); ...
        plot(t,M2,'-','color',a(2,:),'marker',markerStyle); ...
        plot(t,M3,'-','color',a(3,:),'marker',markerStyle); ...
        plot(t,M4,'-','color',a(4,:),'marker',markerStyle); ...
        plot(t,M5, '--','color',a(1,:),'marker',markerStyle); ...
        plot(t,M6, '--','color',a(2,:),'marker',markerStyle); ...
        plot(t,M7, '--','color',a(3,:),'marker',markerStyle); ...
        plot(t,M8, '--','color',a(4,:),'marker',markerStyle); ...
        xlabel('Time [ s ]'); ylabel('Motor Speed'); ...
    xlim(xlims); ylim([100,140]);
    subplot(4,2,4); hold all; grid on; grid minor; ...
        plot(t,M1,'-','color',a(1,:),'marker',markerStyle); ...
        plot(t,M2,'-','color',a(2,:),'marker',markerStyle); ...
        plot(t,M3,'-','color',a(3,:),'marker',markerStyle); ...
        plot(t,M4,'-','color',a(4,:),'marker',markerStyle); ...
        plot(t,M5,'--','color',a(1,:),'marker',markerStyle); ...
        plot(t,M6,'--','color',a(2,:),'marker',markerStyle); ...
        plot(t,M7,'--','color',a(3,:),'marker',markerStyle); ...
        plot(t,M8,'--','color',a(4,:),'marker',markerStyle); ...
        xlabel('Time [ s ]'); ylabel('Motor Speed'); ...
    xlim(xlims); ylim([100,140]);
    subplot(4,2,5); hold all; grid on; grid minor; ...
        plot(t,I1,'-','color',a(1,:),'marker',markerStyle); ...
        plot(t,I2,'-','color',a(2,:),'marker',markerStyle); ...
        plot(t,I3,'-','color',a(3,:),'marker',markerStyle); ...
        plot(t,I4,'-','color',a(4,:),'marker',markerStyle); ...
        plot(t,I5,'--','color',a(1,:),'marker',markerStyle); ...
        plot(t,I6,'--','color',a(2,:),'marker',markerStyle); ...
        plot(t,I7,'--','color',a(3,:),'marker',markerStyle); ...
        plot(t,I8,'--','color',a(4,:),'marker',markerStyle); ...
        xlabel('Time [ s ]'); ylabel('Motor Current');  ...
        xlim(xlims); ylim([15,35]);
    subplot(4,2,6); hold all; grid on; grid minor; ...
        plot(t,M1cmd,'-','color',a(1,:),'marker',markerStyle); ...
        plot(t,M2cmd,'-','color',a(2,:),'marker',markerStyle); ...
        plot(t,M3cmd,'-','color',a(3,:),'marker',markerStyle); ...
        plot(t,M4cmd,'-','color',a(4,:),'marker',markerStyle); ...
        plot(t,M5cmd,'--','color',a(1,:),'marker',markerStyle); ...
        plot(t,M6cmd,'--','color',a(2,:),'marker',markerStyle); ...
        plot(t,M7cmd,'--','color',a(3,:),'marker',markerStyle); ...
        plot(t,M8cmd,'--','color',a(4,:),'marker',markerStyle); ...
        xlabel('Time [ s ]'); ylabel('Motor Speed Command'); ...
    xlim(xlims); ylim([100,140]);
    subplot(4,2,7); hold all; grid on; grid minor; ...
        plot(t,BP1,'-','color',a(1,:),'marker',markerStyle); ...
        plot(t,BP2,'-','color',a(2,:),'marker',markerStyle); ...
        plot(t,BP3,'-','color',a(3,:),'marker',markerStyle); ...
        plot(t,BP4,'-','color',a(4,:),'marker',markerStyle); ...
        plot(t,BP5,'--','color',a(1,:),'marker',markerStyle); ...
        plot(t,BP6,'--','color',a(2,:),'marker',markerStyle); ...
        plot(t,BP7,'--','color',a(3,:),'marker',markerStyle); ...
        plot(t,BP8,'--','color',a(4,:),'marker',markerStyle); ...
        xlabel('Time [ s ]'); ylabel('Blade Pitch'); ...
        xlim(xlims);


    %        keyboard

end